version: "3"

networks:
  alkemio:

services:
  virtual-contributor-engine-guidance:
    container_name: virtual-contributor-engine-guidance
    volumes:
      - "/dev/shm:/dev/shm"
      - "~/alkemio/data:/home/alkemio/data"
    env_file:
      - .env
    image: alkemio/virtual-contributor-engine-guidance:v0.5.1
    depends_on:
      rabbitmq:
        condition: "service_healthy"
    networks:
      - alkemio

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    ports:
      - 5672:5672
      - 8080:15672

    networks:
      - alkemio
