[tool.poetry]
name = "virtual-contributor-engine-guidance"
version = "0.8.1"
description = "Alkemio Generative AI Guidance Engine"
authors = ["Alkemio BV <info@alkem.io>"]
license = "EUPL-1.2"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
langchain = "0.3.9"
langchain-core = "0.3.21"
langchain-community = "0.3.9"
python-dotenv = "1.0.0"
faiss-cpu = "1.7.4"
openai = "1.56.1"
load-dotenv = "0.1.0"
beautifulsoup4 = "4.12.2"
async-timeout = "4.0.3"
aio-pika = "9.3.1"
aiormq = "6.7.7"
tiktoken = "0.8.0"
langchain-openai = "0.2.9"
langchain-mistralai = "0.2.1"
gitpython = "3.1.43"
azure-ai-inference = "1.0.0b6"
alkemio-virtual-contributor-engine = {git = "https://git@github.com/alkem-io/virtual-contributor-engine.git", rev = "v0.0.1"}


[tool.poetry.group.dev.dependencies]
flake8 = "6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

