[tool.poetry]
name = "virtual-contributor-engine-guidance"
version = "0.16.0"
description = "Alkemio Generative AI Guidance Engine"
authors = ["Alkemio BV <info@alkem.io>"]
license = "EUPL-1.2"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
langchain = "^1.1.0"
langchain-core = "^1.1.0"
python-dotenv = "1.1.1"
async-timeout = "5.0.1"
aio-pika = "9.5.7"
aiormq = "6.9.0"
bcrypt = "^5.0.0"
alkemio-virtual-contributor-engine = {git = "https://github.com/alkem-io/virtual-contributor-engine.git", tag = "v0.8.0"}


[tool.poetry.group.dev.dependencies]
flake8 = "7.3.0"
pytest = "^8.0"
pytest-asyncio = "^0.25"
pytest-cov = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

