[tool.poetry]
name = "virtual-contributor-engine-guidance"
version = "0.11.0"
description = "Alkemio Generative AI Guidance Engine"
authors = ["Alkemio BV <info@alkem.io>"]
license = "EUPL-1.2"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
langchain = "0.3.27"
langchain-core = "0.3.78"
langchain-community = "0.3.30"
python-dotenv = "1.1.1"
faiss-cpu = "1.12.0"
openai = "2.2.0"
load-dotenv = "0.1.0"
beautifulsoup4 = "4.14.2"
async-timeout = "5.0.1"
aio-pika = "9.5.7"
aiormq = "6.9.0"
tiktoken = "0.12.0"
langchain-openai = "0.3.35"
langchain-mistralai = "0.2.12"
gitpython = "3.1.45"
azure-ai-inference = "1.0.0b9"
bcrypt = "^5.0.0"
alkemio-virtual-contributor-engine = {git = "https://git@github.com/alkem-io/virtual-contributor-engine.git", rev = "v0.2.0"}


[tool.poetry.group.dev.dependencies]
flake8 = "7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

