name: Build, Migrate & Deploy to Sandbox on Azure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.0.2

      - name: "Login into ACR"
        uses: azure/docker-login@v1.0.1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build & Push image"
        run: |
          docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-virtual-contributor-engine-guidance:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-virtual-contributor-engine-guidance:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-virtual-contributor-engine-guidance:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.0.2

      - name: "Login via Azure CLI"
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}

      - uses: Azure/aks-set-context@v3.2
        with:
          cluster-name: k8s-sandbox
          resource-group: res-grp-k8s-sandbox

      - uses: Azure/k8s-create-secret@v4.0
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: alkemio-virtual-contributor-engine-guidance-secret

      - uses: azure/setup-kubectl@v3.2
        with:
          version: "v1.22.0" # default is latest stable, fixing it to a compatible version
        id: install

      - uses: Azure/k8s-deploy@v4.10
        with:
          manifests: |
            manifests/25-genai-deployment-dev.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-virtual-contributor-engine-guidance:${{ github.sha }}
          imagepullsecrets: |
            alkemio-virtual-contributor-engine-guidance-secret
